# Generated by Django 3.2.7 on 2022-01-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_addtocart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsitem',
            name='brand',
            field=models.CharField(choices=[('Local', 'Local'), ('Branded', 'Branded'), ('Imported', 'Imported')], max_length=255),
        ),
    ]
