# Generated by Django 3.2.7 on 2022-01-29 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0003_alter_productsitem_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='product',
        ),
        migrations.AddField(
            model_name='addtocart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.productsitem'),
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Add_to_Car', to=settings.AUTH_USER_MODEL),
        ),
    ]
